# Generated by Django 5.1.7 on 2025-03-28 06:37

import django.db.models.deletion
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=store.models.Category.get_default_category, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category'),
        ),
    ]
