# Generated by Django 5.1.7 on 2025-04-04 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="products_info",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
    ]
